# Tell Python build system about required tools.
# Leave unchanged.

[build-system]
requires = [
    "setuptools",
    "wheel",
    "prettytable",
    "matplotlib",
    "numba"
]
build-backend = "setuptools.build_meta"
